version: '3.8'
services:
  
      
  besuval0:
    image: hyperledger/besu:21.1
    container_name: besuval0
    working_dir: /wrk
    ports:
      - '30300:30300'
      - '8545:8545'
      - '5555:5555'
    entrypoint:
      - /bin/sh
      - -c
      - |
        besu --identity=besuval0 \
        --nat-method=NONE \
        --logging=INFO \
        --miner-enabled \
        --miner-coinbase=0x6c5299909cbf3a6e06c2770e80cf55933e3c13fd \
        --min-gas-price=0 \
        --p2p-host=10.0.2.100 \
        --p2p-interface=0.0.0.0 \
        --p2p-port=30300 \
        --data-path=data \
        --genesis-file=./networkFiles/genesis.json \
        --discovery-enabled=true \
        --rpc-http-enabled \
        --rpc-http-host=0.0.0.0 \
         --rpc-http-port=8545 \
         --rpc-http-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT \
         --host-allowlist="*" \
         --rpc-http-cors-origins="all" \
         --rpc-ws-enabled \
         --rpc-ws-host=0.0.0.0 \
         --rpc-ws-port=5555 \
         --rpc-ws-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT 
    volumes:
      - ./networkFiles:/wrk/networkFiles
      - ./n0/data:/wrk/data
    networks:
      byfn:
        ipv4_address: 10.0.2.100

    
  besuval1:
    image: hyperledger/besu:21.1
    container_name: besuval1
    working_dir: /wrk
    ports:
      - '30301:30300'
      - '8546:8545'
      - '5556:5555'
    entrypoint:
      - /bin/sh
      - -c
      - |
        besu --identity=besuval1 \
        --nat-method=NONE \
        --bootnodes="enode://4d1f123f8c276d0746eef6fc3546282475cc1c6a400f218174f5ce42be73c6871cdf8a761137f01cc30ba3e8c23c66b0a12508e97d1661de3a9b4313aa42428e@10.0.2.100:30300" \
        --logging=INFO \
        --miner-enabled \
        --miner-coinbase=0x8cab1f91c9b8405bfb4100d3ef942d2d73acde02 \
        --min-gas-price=0 \
        --p2p-host=10.0.2.101 \
        --p2p-interface=0.0.0.0 \
        --p2p-port=30300 \
        --data-path=data \
        --genesis-file=./networkFiles/genesis.json \
        --discovery-enabled=true \
        --rpc-http-enabled \
        --rpc-http-host=0.0.0.0 \
         --rpc-http-port=8545 \
         --rpc-http-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT \
         --host-allowlist="*" \
         --rpc-http-cors-origins="all" \
         --rpc-ws-enabled \
         --rpc-ws-host=0.0.0.0 \
         --rpc-ws-port=5555 \
         --rpc-ws-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT
    volumes:
      - ./networkFiles:/wrk/networkFiles
      - ./n1/data:/wrk/data
    networks:
      byfn:
        ipv4_address: 10.0.2.101

  besuval2:
    image: hyperledger/besu:21.1
    container_name: besuval2
    working_dir: /wrk
    ports:
      - '30302:30300'
      - '8547:8545'
      - '5557:5555'
    entrypoint:
      - /bin/sh
      - -c
      - |
        besu --identity=besuval2 \
        --nat-method=NONE \
        --bootnodes="enode://4d1f123f8c276d0746eef6fc3546282475cc1c6a400f218174f5ce42be73c6871cdf8a761137f01cc30ba3e8c23c66b0a12508e97d1661de3a9b4313aa42428e@10.0.2.100:30300,enode://fc66e9904089661dd29e6d2ad375d724aa58c2ffc92d314b72b0ab70a464848dcdfaeb2780eaa8ab811504747276f7481668d3cc43b826dfe9408bd46b2dbe42@10.0.2.101:30300" \
        --logging=INFO \
        --miner-enabled \
        --miner-coinbase=0x204302f2df77398cb8cc3972e9d45107fd65dff7 \
        --min-gas-price=0 \
        --p2p-host=10.0.2.102 \
        --p2p-interface=0.0.0.0 \
        --p2p-port=30300 \
        --data-path=data \
        --genesis-file=./networkFiles/genesis.json \
        --discovery-enabled=true \
        --rpc-http-enabled \
        --rpc-http-host=0.0.0.0 \
         --rpc-http-port=8545 \
         --rpc-http-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT \
         --host-allowlist="*" \
         --rpc-http-cors-origins="all" \
         --rpc-ws-enabled \
         --rpc-ws-host=0.0.0.0 \
         --rpc-ws-port=5555 \
         --rpc-ws-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT
    volumes:
      - ./networkFiles:/wrk/networkFiles
      - ./n2/data:/wrk/data
    networks:
      byfn:
        ipv4_address: 10.0.2.102
      
  besuval3:
    image: hyperledger/besu:21.1
    container_name: besuval3
    working_dir: /wrk
    ports:
      - '30303:30300'
      - '8548:8545'
      - '5558:5555'
    entrypoint:
      - /bin/sh
      - -c
      - |
        besu --identity=besuval3 \
        --nat-method=NONE \
        --bootnodes="enode://4d1f123f8c276d0746eef6fc3546282475cc1c6a400f218174f5ce42be73c6871cdf8a761137f01cc30ba3e8c23c66b0a12508e97d1661de3a9b4313aa42428e@10.0.2.100:30300,enode://fc66e9904089661dd29e6d2ad375d724aa58c2ffc92d314b72b0ab70a464848dcdfaeb2780eaa8ab811504747276f7481668d3cc43b826dfe9408bd46b2dbe42@10.0.2.101:30300,enode://eeb5ea7394a70421ff2c70d678ed444e52222c85e26e3a7a8f50c5d47e8e0ab2a206cfca168f640838d54fbbce8e0957b206ea9be201ecab8b5f4b986124a92f@10.0.2.102:30300" \
        --logging=INFO \
        --miner-enabled \
        --miner-coinbase=0xcb876241721e70692a8d961fd84d02039888493c \
        --min-gas-price=0 \
        --p2p-host=10.0.2.103 \
        --p2p-interface=0.0.0.0 \
        --p2p-port=30300 \
        --data-path=data \
        --genesis-file=./networkFiles/genesis.json \
        --discovery-enabled=true \
        --rpc-http-enabled \
        --rpc-http-host=0.0.0.0 \
         --rpc-http-port=8545 \
         --rpc-http-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT \
         --host-allowlist="*" \
         --rpc-http-cors-origins="all" \
         --rpc-ws-enabled \
         --rpc-ws-host=0.0.0.0 \
         --rpc-ws-port=5555 \
         --rpc-ws-api=ADMIN,DEBUG,ETH,NET,WEB3,IBFT
    volumes:
      - ./networkFiles:/wrk/networkFiles
      - ./n3/data:/wrk/data
    networks:
      byfn:
        ipv4_address: 10.0.2.103

networks:
  byfn:
    external: true
